services:
  # Contact Form CMS Service
  cms-contact-form:
    build: .
    image: cms-contact-form:1.0.0
    container_name: cms-contact-form
    restart: unless-stopped
    environment:
      - API_CONTACT_FORM_BASE_URI=http://host.docker.internal:8080/contacts
      - SESSION_DRIVER=file
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - nginx-cms-contact-form
    networks:
      - contact-form-network-cms

  # Nginx Web Server for Contact Form CMS
  nginx-cms-contact-form:
    image: nginx:alpine
    container_name: nginx-cms-contact-form
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - contact-form-network-cms

networks:
  contact-form-network-cms:
    driver: bridge